[package]
name = "griddy_contracts"
version = "0.1.0"
edition = "2023_11"

[dependencies]
openzeppelin = {git = "https://github.com/OpenZeppelin/cairo-contracts.git", version = "0.20.0-rc.0"}

[[target.starknet-contract]]
sierra = true
casm = true